backend/chat/api/urls.py
from django.urls import path

from chat.api import views

urlpatterns = [
    path('message/', views.MessageList.as_view()),
    path('message/create/', views.MessageCreate.as_view()),
    path('message/<int:pk>', views.MessageDetail.as_view()),
    path('room/', views.RoomList.as_view()),
    path('room/create/', views.RoomCreate.as_view()),
    path('room/<int:pk>/', views.RoomDetail.as_view())
]

backend/chat/urls.py
from django.urls import path,include
from chat import views
from django.contrib.auth import views as vi
from django.urls import reverse_lazy
app_name = 'chat'
urlpatterns = [
    path('', views.base, name='index'),
    path('chat/', views.index, name='index'),
    path('chat/<str:room_name>/', views.room, name='room'),
]

backend/oto/api/urls.py
from django.urls import path

from oto.api import views

urlpatterns = [
    path('', views.ChatList.as_view()),
    path('create/', views.ChatCreate.as_view()),
    path('<int:pk>', views.ChatDetail.as_view())
]

backend/oto/urls.py
from django.urls import path,include
from oto import views
from django.contrib.auth import views as vi
from django.urls import reverse_lazy
app_name = 'oto'
urlpatterns = [
    # path('', views.base, name='index'),
    path('chat/', views.index, name='index'),
    # path('chat/<str:room_name>/', views.room, name='room'),
]

backend/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django_registration.backends.activation.views import RegistrationView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('oto/', include('oto.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('api/oto/', include('oto.api.urls')),
    path('api/chat/', include('chat.api.urls')),
    # path("accounts/profile/", blango_auth.views.profile, name="profile"),
    path("accounts/register/", RegistrationView.as_view(),name="django_registration_register"),
    path("accounts/", include("django_registration.backends.activation.urls")),
    # path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += [
    path('__debug__/', include('debug_toolbar.urls')),
    ]

backend/chat/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Room(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name 

class Message(models.Model):
    user = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE)
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(Room, related_name='message_room', on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f"{self.user.username[:10]}: {self.content[:10]}"

backend/oto/models.py
from pyexpat.errors import messages
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Contact(models.Model):
    user = models.ForeignKey(User, related_name= 'friends', on_delete=models.CASCADE)
    friends = models.ManyToManyField('self', blank=True)
    def __str__(self):
        return str(self.user.friends)

class Message(models.Model):
    contact = models.ForeignKey(Contact, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.contact}: {self.content}"
class Chat(models.Model):
    participants = models.ManyToManyField(Contact, related_name='chats')
    messages = models.ManyToManyField(Message, blank=True)
    def __str__(self):
        return f'{self.pk}'

backend/chat/api/views.py
from rest_framework import generics
from rest_framework import permissions
from rest_framework.authentication import SessionAuthentication
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from chat.api.serializers import MessageSerializer, RoomSerializer
from chat.models import Room, Message
# from oto.api.permissions import AuthorModifyOrReadOnly, IsAdminUserForObject

User = get_user_model()

class RoomList(generics.ListAPIView):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    permission_classes = [permissions.AllowAny]

class RoomCreate(generics.CreateAPIView):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer

class RoomDetail(generics.RetrieveUpdateDestroyAPIView):
    # permission_classes = (permissions.isAuthenticated,) #type: ignore
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    
class MessageList(generics.ListAPIView):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer
    permission_classes = [permissions.AllowAny]

class MessageCreate(generics.CreateAPIView):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer

class MessageDetail(generics.RetrieveUpdateDestroyAPIView):
    # permission_classes = (permissions.isAuthenticated,) #type: ignore
    queryset = Message.objects.all()
    serializer_class = MessageSerializer

backend/chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Room
def index(request):
    rooms = Room.objects.all()
    ctx = {'rooms': rooms}
    return render(request, 'chat/index.html', ctx)
def base(request):
    return render(request, 'base.html')


@login_required
def room(request, room_name):
    room = get_object_or_404(Room, name=room_name)
    rooms = Room.objects.all()
    return render(request, 'chat/room.html', {
        'room_name': room.name,
        'rooms': rooms,
        'username': request.user.username
    })

backend/oto/api/views.py
from rest_framework import generics
from rest_framework import permissions
from rest_framework.authentication import SessionAuthentication
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from oto.api.serializers import ChatSerializer
from oto.models import Chat, Contact
# from oto.api.permissions import AuthorModifyOrReadOnly, IsAdminUserForObject

User = get_user_model()
def get_user_contact(username):
    user = get_object_or_404(User, username=username)
    contact = get_object_or_404(Contact, user=user)
    return contact

class ChatList(generics.ListAPIView):
    # queryset = Chat.objects.all()
    serializer_class = ChatSerializer
    permission_classes = [permissions.AllowAny]

    def get_queryset(self):
        queryset = Chat.objects.all()
        print(queryset)
        username = self.request.query_params.get('username', None)
        if username is not None:
            contact = get_user_contact(username)
            queryset = contact.chats.all()
        return queryset
class ChatCreate(generics.CreateAPIView):
    queryset = Chat.objects.all()
    serializer_class = ChatSerializer

class ChatDetail(generics.RetrieveUpdateDestroyAPIView):
    # permission_classes = (permissions.isAuthenticated,) #type: ignore
    queryset = Chat.objects.all()
    serializer_class = ChatSerializer

backend/oto/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Contact, Message, Chat
# Create your views here.
def index(request):
    contact = get_object_or_404(Contact, user=request.user)
    contact = contact.chats.all() #type:ignore
    print(contact)
    ctx = {'friends': contact}
    return render(request, 'chat/index.html', ctx)


# def base(request):
#     return render(request, 'base.html')


# # @login_required
# # def room(request, room_name):
# #     room = get_object_or_404(Room, name=room_name)
# #     rooms = Room.objects.all()
# #     return render(request, 'chat/room.html', {
# #         'room_name': room.name,
# #         'rooms': rooms,
# #         'username': request.user.username
# #     })

backend/templates/base.html
{%load static%}

<!DOCTYPE html>
<html>
    <head>
        <title> {% block title %}Chat{% endblock title %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">		
        <link rel="stylesheet" href="{%static 'style.css'%}">
        <link rel="stylesheet" href="{%static 'navbar.css'%}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{%static 'reconnecting-websocket.js'%}"></script>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!------ Include the above in your HEAD tag ---------->

	</head>
	<!--Coded With Love By Mutiullah Samim-->
	<body>
        {% include "parts/navbar.html" %}

                        {% block body %}
                        
                        {% endblock body %}
					

		</div>
	</body>
    
    
</html>

backend/templates/django_registration/registration_form.html
{%extends 'base.html' %}

{%block title%} Register {%endblock title%}
{%block body%}
{% if user.is_authenticated %}
        <meta http-equiv = "refresh" content = "0; url = {%url 'chat:index'%}"/>
{%else%}
<div>
    <section class=" container position-relative py-4 py-xl-5">
        <div class="container position-relative">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="font-weight-bold">Register</h2>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-6">
                    <div class="card">
                        <div class="card-body text-center d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div>

                            <form method="post" novalidate">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{next}}">
                                {%include 'parts/form.html'%}
                                <button type='submit' class="btn btn-primary d-block w-100">Register</button>
                            </form>
                        </div>
                    </div>
                    <br>
                    <h5 style="text-align: center;">Already have an account <a href="{%url 'login'%}">Login</a> </h5>
                </div>
            </div>
        </div>
    </section>

</div>
{% endif %}

{%endblock body%}

backend/templates/oto/index.html
{% extends "base.html" %}

{% block body %}
<div class="container-fluid h-100">
    <div class="row justify-content-center h-100">
        <div class="col-md-4 col-xl-3 chat"><div class="card mb-sm-3 mb-md-0 contacts_card">
            <div class="card-header">
                <div class="input-group">
                    <input id="room-name-input" type="text" placeholder="Enter room name..." name="" class="form-control search">
                    
                    <div id= "room-name-submit" class="input-group-prepend">
                        <span class="input-group-text search_btn"><i class="fas fa-search"></i></span>
                    </div>
                    <script>
                        document.querySelector('#room-name-input').focus();
                        document.querySelector('#room-name-input').onkeyup = function(e) {
                            if (e.keyCode === 13) {  // enter, return
                                document.querySelector('#room-name-submit').click();
                            }
                        };

                        document.querySelector('#room-name-submit').onclick = function(e) {
                            var roomName = document.querySelector('#room-name-input').value;
                            window.location.pathname = '/chat/' + roomName + '/';
                        };
                    </script>
                </div>
            </div>
            <div class="card-body contacts_body">
                <ui id= 'rooms' class="contacts">
                {% for room in rooms %}
                    {% if room_name == room.name %}
                        <li class="active">
                            <div class="d-flex bd-highlight">
                                <div class="img_cont">
                                    <img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img">
                                    <span class="online_icon"></span>
                                </div>
                                <div class="user_info">
                                    <span>{{room.name}}</span>
                                    <p>{{room.name}} is online</p>
                                </div>
                            </div>
                        </li>
                    {%else%}
                    <li>
                        <a style= 'text-decoration: none' href="{%url 'chat:room' room_name=room.name  %}">
                        <div class="d-flex bd-highlight">
                            <div class="img_cont">
                                <img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img">
                                <span class="online_icon"></span>
                            </div>
                            <div class="user_info">
                                <span>{{room.name}}</span>
                                <p>{{room.name}} is online</p>
                            </div>
                        </div>
                        </a>
                    </li>
                    {% endif %}

                {% endfor %}
                
                </ui>
            </div>
            {% block chat %}
            
            {% endblock chat %}
{% endblock body %}

backend/templates/oto/room.html
{%extends 'chat/index.html'%}
{%load static%}
{% block chat %}
<div class="card-footer"></div>
</div></div>
<div class="col-md-8 col-xl-6 chat">
    <div class="card">
        <div class="card-header msg_head">
            <div class="d-flex bd-highlight">
                <div class="img_cont">
                    <img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img">
                    <span class="online_icon"></span>
                </div>
                <div class="user_info">
                    <span>{{room_name}}</span>
                </div>
            </div>
            <span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
            <div class="action_menu">
                <ul>
                    <li><i class="fas fa-user-circle"></i> View profile</li>
                    <li><i class="fas fa-users"></i> Add to close friends</li>
                    <li><i class="fas fa-plus"></i> Add to group</li>
                    <li><i class="fas fa-ban"></i> Block</li>
                </ul>
            </div>
        </div>
        <div id='msgs-body' class="card-body msg_card_body">

        </div>
        <div class="card-footer">
            <div class="input-group">
                <div class="input-group-append">
                    <span class="input-group-text attach_btn"><i class="fas fa-paperclip"></i></span>
                </div>
                <input type="text" id = "chat-message-input" name="" class="form-control type_msg" placeholder="Type your message...">
                <div id ="chat-message-submit" class="input-group-append">
                    <span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{{ room_name|json_script:"room-name" }}
{{ username|json_script:"username" }}
<script>
    const roomName = JSON.parse(document.getElementById('room-name').textContent);
    const userName = JSON.parse(document.getElementById('username').textContent);
    var username = "{{username}}";
    const chatSocket = new ReconnectingWebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );
    chatSocket.onopen = function(e) {
        fetchMessage();
    }
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        if(data["command"] === 'messages'){
            data['messages'].reverse()
            for (var i = 0; i < data['messages'].length; i++) {
                createMessage(data['messages'][i]);
            }
            var element = document.getElementById('msgs-body');
            element.scrollTop = element.scrollHeight;
        }else if(data["command"] === 'new_message'){
            createMessage(data["message"])
            var element = document.getElementById('msgs-body');
            element.scrollTop = element.scrollHeight;
        }
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'command': 'new_message',
            'message': message,
            'from': "{{username}}",
            'room': roomName
        }));
        messageInputDom.value = '';
    };
    function fetchMessage(){
        chatSocket.send(JSON.stringify(
            {'command': 'fetch_messages',
            'room': roomName
            }
            ));
    }
    function createMessage(data){
        var message = data.content;
        var user = data.user;
        var time = data.time;
        var msgDivTag = document.createElement('div');
        var divFtTag = document.createElement('div');
        var spanTag = document.createElement('span');
        if (user === username){
            msgDivTag.className='d-flex justify-content-end mb-4';
            divFtTag.className = 'msg_cotainer_send';
            spanTag.className = 'msg_time_send';
            spanTag.textContent = 'by me'
        }else{
            msgDivTag.className='d-flex justify-content-start mb-4';
            divFtTag.className = 'msg_cotainer';
            spanTag.className = 'msg_time';
            spanTag.textContent = "by " + user;
        }
        divFtTag.textContent =message;
        divFtTag.appendChild(spanTag);
        msgDivTag.appendChild(divFtTag);
        document.querySelector('#msgs-body').appendChild(msgDivTag);
    }

</script>
<script src="{%static 'main.js'%}"></script>
{% endblock chat %}

backend/templates/parts/form.html
{%load widget_tweaks%}
{% if form.non_field_errors%}
<div class="alert alert-danger" role="alert">
    {%for error in form.non_field_errors%}
        
    {% if forloop.last%}

        <p class="mb-0">{{error}}</p>
        {%endif%}
    {%endfor%}
</div>
{%endif%}
{%for field in form%}
<div class="form-group">
    {{field.label_tag}}
    {%if form.is_bound%}
        {%if field.errors%}
        {%render_field field class="form-control is_invalid" style="border: 1px solid red;"%}
            {%for error in field.errors%}
                <div class="invalid-feedback">{{error}}</div>
            {%endfor%}
        {%else%}
            {%render_field field class="form-control is_valid" style="border: 1px solid green;"%}
        {%endif%}
    {%else%}
    {%render_field field class="form-control"%}
    {%endif%}
</div>
{%endfor%}

backend/templates/parts/navbar.html
<nav class="navbar navbar-expand-xl navbar-light bg-light">
    <a href="{%url 'chat:index'%}" class="navbar-brand"><i class="fa fa-cube"></i>Chat<b>You</b></a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Collection of nav links, forms, and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
        <div class="navbar-nav">
            <a href="{%url 'chat:index'%}" class="nav-item nav-link active">Home</a>
            <a href="{%url 'chat:index'%}" class="nav-item nav-link active">Rooms</a>
            <a href="{%url 'oto:index'%}" class="nav-item nav-link">Friends</a>
            <a href="#" class="nav-item nav-link">Contact</a>
        </div>
        <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        
            <a href="#" class="nav-item nav-link notifications"><i class="fa fa-bell-o"></i><span class="badge">1</span></a>
            <a href="#" class="nav-item nav-link messages"><i class="fa fa-envelope-o"></i><span class="badge">10</span></a></a>

            <div class="nav-item dropdown">
                <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle user-action"><img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_1280.png" class="avatar" alt="Avatar"> {{user.username}} <b class="caret"></b></a>
                <div class="dropdown-menu">
                    <a href="#" class="dropdown-item"><i class="fa fa-user-o"></i> Profile</a></a>
                    <a href="#" class="dropdown-item"><i class="fa fa-calendar-o"></i> Calendar</a></a>
                    <a href="#" class="dropdown-item"><i class="fa fa-sliders"></i> Settings</a></a>
                    <div class="dropdown-divider"></div>
                    <a href="{%url 'logout'%}" class="dropdown-item"><i class="material-icons">&#xE8AC;</i> Logout</a></a>
                </div>
            </div>
        </div>
        {%else%}
            <a href="{%url 'login'%}" class="nav-item nav-link">Login</a>
            <a href="{%url 'django_registration_register'%}" class="nav-item nav-link">Register</a>
        {% endif %}
    </div>
        
    </div>
</nav>